{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "id": "KQhwL5yxnq0O"
   },
   "outputs": [],
   "source": [
    "# Define the the three inputs needed for any RAG evaluation\n",
    "\n",
    "wikipedia_text = \"\"\"\n",
    "A large language model (LLM) is a machine learning model designed for natural language processing tasks, especially language generation.\n",
    "LLMs are language models with many parameters, and are trained with self-supervised learning on a vast amount of text.\n",
    "\n",
    "The largest and most capable LLMs are generative pretrained transformers (GPTs), which are largely used in generative chatbots such as ChatGPT or Gemini.\n",
    "LLMs can be fine-tuned for specific tasks or guided by prompt engineering. These models acquire predictive power regarding syntax, semantics, and\n",
    "ontologies inherent in human language corpora, but they also inherit inaccuracies and biases present in the data they are trained in.\n",
    "\"\"\"\n",
    "\n",
    "\n",
    "question = \"Which large language model is currently the largest and most capable?\"\n",
    "\n",
    "\n",
    "llm_response = \"\"\"\n",
    "The largest and most capable LLMs are the generative pretrained transformers (GPTs). These models are\n",
    "designed to handle complex language tasks, and their vast number of parameters gives them the ability to\n",
    "understand and generate human-like text.\n",
    "\"\"\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'OPENAI_API_KEY': 'REMOVED'}\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "from pprint import pprint\n",
    "\n",
    "# List all environment variables containing 'API_KEY'\n",
    "api_keys = {k: v for k, v in os.environ.items() if 'API_KEY' in k}\n",
    "\n",
    "pprint(api_keys)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "id": "nPi8SoJ1_OjV"
   },
   "source": [
    "# Environment Setup and API Key Configuration"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {
    "id": "hJMuPQ522DwI"
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING: There was an error checking the latest version of pip.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "REMOVED\n",
      "AIzaSyAYhhtxaW3YV2Eo-bctJGTkLrpqlC-8RQc\n"
     ]
    }
   ],
   "source": [
    "!pip install -q python-dotenv\n",
    "\n",
    "from dotenv import load_dotenv\n",
    "load_dotenv()\n",
    "import os\n",
    "\n",
    "\n",
    "# Set the OpenAI API key env variable manually\n",
    "os.environ[\"OPENAI_API_KEY\"] = \"REMOVED\"\n",
    "os.environ[\"GEMINI_API_KEY\"] = \"AIzaSyAYhhtxaW3YV2Eo-bctJGTkLrpqlC-8RQc\"\n",
    "\n",
    "print(os.environ[\"OPENAI_API_KEY\"])\n",
    "print(os.environ[\"GEMINI_API_KEY\"])"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "id": "Jp6hHmzSDEBU"
   },
   "source": [
    "# Import RAG_Evaluation package"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/"
    },
    "id": "DOJF1Lgv2uTa",
    "outputId": "c3a34597-7ff1-4fbd-c8e3-33d13a5df914"
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting rag_evaluation==0.2.1\n",
      "  Obtaining dependency information for rag_evaluation==0.2.1 from https://files.pythonhosted.org/packages/4b/d7/5293acfa89fcfeca88a30b4ca5528de212c1fb1520665959389c4b048531/rag_evaluation-0.2.1-py3-none-any.whl.metadata\n",
      "  Using cached rag_evaluation-0.2.1-py3-none-any.whl.metadata (5.7 kB)\n",
      "Requirement already satisfied: numpy in c:\\python312\\lib\\site-packages (from rag_evaluation==0.2.1) (1.26.4)\n",
      "Requirement already satisfied: pandas>=1.0 in c:\\python312\\lib\\site-packages (from rag_evaluation==0.2.1) (2.2.2)\n",
      "Requirement already satisfied: openai>=0.27 in c:\\python312\\lib\\site-packages (from rag_evaluation==0.2.1) (0.28.0)\n",
      "Requirement already satisfied: python-dotenv>=0.21 in c:\\python312\\lib\\site-packages (from rag_evaluation==0.2.1) (1.0.1)\n",
      "Collecting google-genai>=0.1.0 (from rag_evaluation==0.2.1)\n",
      "  Obtaining dependency information for google-genai>=0.1.0 from https://files.pythonhosted.org/packages/f6/ec/149f3d49b56cf848142071772aabb1c290b535bd9b5327a5dfccf1d00332/google_genai-1.25.0-py3-none-any.whl.metadata\n",
      "  Using cached google_genai-1.25.0-py3-none-any.whl.metadata (41 kB)\n",
      "Requirement already satisfied: transformers>=4.30.0 in c:\\python312\\lib\\site-packages (from rag_evaluation==0.2.1) (4.45.1)\n",
      "Requirement already satisfied: torch>=2.0.0 in c:\\users\\hp\\appdata\\roaming\\python\\python312\\site-packages (from rag_evaluation==0.2.1) (2.2.2)\n",
      "Collecting accelerate>=0.20.0 (from rag_evaluation==0.2.1)\n",
      "  Obtaining dependency information for accelerate>=0.20.0 from https://files.pythonhosted.org/packages/91/d9/e044c9d42d8ad9afa96533b46ecc9b7aea893d362b3c52bd78fb9fe4d7b3/accelerate-1.8.1-py3-none-any.whl.metadata\n",
      "  Using cached accelerate-1.8.1-py3-none-any.whl.metadata (19 kB)\n",
      "Requirement already satisfied: sentencepiece>=0.1.97 in c:\\python312\\lib\\site-packages (from rag_evaluation==0.2.1) (0.2.0)\n",
      "Requirement already satisfied: protobuf>=3.20.0 in c:\\python312\\lib\\site-packages (from rag_evaluation==0.2.1) (6.31.1)\n",
      "Requirement already satisfied: packaging>=20.0 in c:\\python312\\lib\\site-packages (from accelerate>=0.20.0->rag_evaluation==0.2.1) (24.0)\n",
      "Requirement already satisfied: psutil in c:\\users\\hp\\appdata\\roaming\\python\\python312\\site-packages (from accelerate>=0.20.0->rag_evaluation==0.2.1) (5.9.8)\n",
      "Requirement already satisfied: pyyaml in c:\\python312\\lib\\site-packages (from accelerate>=0.20.0->rag_evaluation==0.2.1) (6.0.1)\n",
      "Requirement already satisfied: huggingface_hub>=0.21.0 in c:\\python312\\lib\\site-packages (from accelerate>=0.20.0->rag_evaluation==0.2.1) (0.25.1)\n",
      "Requirement already satisfied: safetensors>=0.4.3 in c:\\python312\\lib\\site-packages (from accelerate>=0.20.0->rag_evaluation==0.2.1) (0.4.5)\n",
      "Collecting anyio<5.0.0,>=4.8.0 (from google-genai>=0.1.0->rag_evaluation==0.2.1)\n",
      "  Obtaining dependency information for anyio<5.0.0,>=4.8.0 from https://files.pythonhosted.org/packages/a1/ee/48ca1a7c89ffec8b6a0c5d02b89c305671d5ffd8d3c94acf8b8c408575bb/anyio-4.9.0-py3-none-any.whl.metadata\n",
      "  Using cached anyio-4.9.0-py3-none-any.whl.metadata (4.7 kB)\n",
      "Collecting google-auth<3.0.0,>=2.14.1 (from google-genai>=0.1.0->rag_evaluation==0.2.1)\n",
      "  Obtaining dependency information for google-auth<3.0.0,>=2.14.1 from https://files.pythonhosted.org/packages/17/63/b19553b658a1692443c62bd07e5868adaa0ad746a0751ba62c59568cd45b/google_auth-2.40.3-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_auth-2.40.3-py2.py3-none-any.whl.metadata (6.2 kB)\n",
      "Collecting httpx<1.0.0,>=0.28.1 (from google-genai>=0.1.0->rag_evaluation==0.2.1)\n",
      "  Obtaining dependency information for httpx<1.0.0,>=0.28.1 from https://files.pythonhosted.org/packages/2a/39/e50c7c3a983047577ee07d2a9e53faf5a69493943ec3f6a384bdc792deb2/httpx-0.28.1-py3-none-any.whl.metadata\n",
      "  Using cached httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)\n",
      "Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in c:\\python312\\lib\\site-packages (from google-genai>=0.1.0->rag_evaluation==0.2.1) (2.9.2)\n",
      "Requirement already satisfied: requests<3.0.0,>=2.28.1 in c:\\users\\hp\\appdata\\roaming\\python\\python312\\site-packages (from google-genai>=0.1.0->rag_evaluation==0.2.1) (2.32.2)\n",
      "Requirement already satisfied: tenacity<9.0.0,>=8.2.3 in c:\\python312\\lib\\site-packages (from google-genai>=0.1.0->rag_evaluation==0.2.1) (8.5.0)\n",
      "Requirement already satisfied: websockets<15.1.0,>=13.0.0 in c:\\python312\\lib\\site-packages (from google-genai>=0.1.0->rag_evaluation==0.2.1) (15.0.1)\n",
      "Requirement already satisfied: typing-extensions<5.0.0,>=4.11.0 in c:\\python312\\lib\\site-packages (from google-genai>=0.1.0->rag_evaluation==0.2.1) (4.12.2)\n",
      "Requirement already satisfied: tqdm in c:\\python312\\lib\\site-packages (from openai>=0.27->rag_evaluation==0.2.1) (4.66.2)\n",
      "Requirement already satisfied: aiohttp in c:\\python312\\lib\\site-packages (from openai>=0.27->rag_evaluation==0.2.1) (3.10.8)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in c:\\python312\\lib\\site-packages (from pandas>=1.0->rag_evaluation==0.2.1) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2020.1 in c:\\python312\\lib\\site-packages (from pandas>=1.0->rag_evaluation==0.2.1) (2024.1)\n",
      "Requirement already satisfied: tzdata>=2022.7 in c:\\python312\\lib\\site-packages (from pandas>=1.0->rag_evaluation==0.2.1) (2024.1)\n",
      "Requirement already satisfied: filelock in c:\\users\\hp\\appdata\\roaming\\python\\python312\\site-packages (from torch>=2.0.0->rag_evaluation==0.2.1) (3.13.3)\n",
      "Requirement already satisfied: sympy in c:\\python312\\lib\\site-packages (from torch>=2.0.0->rag_evaluation==0.2.1) (1.12)\n",
      "Requirement already satisfied: networkx in c:\\users\\hp\\appdata\\roaming\\python\\python312\\site-packages (from torch>=2.0.0->rag_evaluation==0.2.1) (3.2.1)\n",
      "Requirement already satisfied: jinja2 in c:\\users\\hp\\appdata\\roaming\\python\\python312\\site-packages (from torch>=2.0.0->rag_evaluation==0.2.1) (3.1.3)\n",
      "Requirement already satisfied: fsspec in c:\\users\\hp\\appdata\\roaming\\python\\python312\\site-packages (from torch>=2.0.0->rag_evaluation==0.2.1) (2024.3.1)\n",
      "Requirement already satisfied: regex!=2019.12.17 in c:\\python312\\lib\\site-packages (from transformers>=4.30.0->rag_evaluation==0.2.1) (2024.9.11)\n",
      "Requirement already satisfied: tokenizers<0.21,>=0.20 in c:\\python312\\lib\\site-packages (from transformers>=4.30.0->rag_evaluation==0.2.1) (0.20.0)\n",
      "Requirement already satisfied: idna>=2.8 in c:\\users\\hp\\appdata\\roaming\\python\\python312\\site-packages (from anyio<5.0.0,>=4.8.0->google-genai>=0.1.0->rag_evaluation==0.2.1) (3.7)\n",
      "Requirement already satisfied: sniffio>=1.1 in c:\\python312\\lib\\site-packages (from anyio<5.0.0,>=4.8.0->google-genai>=0.1.0->rag_evaluation==0.2.1) (1.3.1)\n",
      "Collecting cachetools<6.0,>=2.0.0 (from google-auth<3.0.0,>=2.14.1->google-genai>=0.1.0->rag_evaluation==0.2.1)\n",
      "  Obtaining dependency information for cachetools<6.0,>=2.0.0 from https://files.pythonhosted.org/packages/72/76/20fa66124dbe6be5cafeb312ece67de6b61dd91a0247d1ea13db4ebb33c2/cachetools-5.5.2-py3-none-any.whl.metadata\n",
      "  Using cached cachetools-5.5.2-py3-none-any.whl.metadata (5.4 kB)\n",
      "Collecting pyasn1-modules>=0.2.1 (from google-auth<3.0.0,>=2.14.1->google-genai>=0.1.0->rag_evaluation==0.2.1)\n",
      "  Obtaining dependency information for pyasn1-modules>=0.2.1 from https://files.pythonhosted.org/packages/47/8d/d529b5d697919ba8c11ad626e835d4039be708a35b0d22de83a269a6682c/pyasn1_modules-0.4.2-py3-none-any.whl.metadata\n",
      "  Using cached pyasn1_modules-0.4.2-py3-none-any.whl.metadata (3.5 kB)\n",
      "Collecting rsa<5,>=3.1.4 (from google-auth<3.0.0,>=2.14.1->google-genai>=0.1.0->rag_evaluation==0.2.1)\n",
      "  Obtaining dependency information for rsa<5,>=3.1.4 from https://files.pythonhosted.org/packages/64/8d/0133e4eb4beed9e425d9a98ed6e081a55d195481b7632472be1af08d2f6b/rsa-4.9.1-py3-none-any.whl.metadata\n",
      "  Using cached rsa-4.9.1-py3-none-any.whl.metadata (5.6 kB)\n",
      "Requirement already satisfied: certifi in c:\\users\\hp\\appdata\\roaming\\python\\python312\\site-packages (from httpx<1.0.0,>=0.28.1->google-genai>=0.1.0->rag_evaluation==0.2.1) (2024.2.2)\n",
      "Requirement already satisfied: httpcore==1.* in c:\\python312\\lib\\site-packages (from httpx<1.0.0,>=0.28.1->google-genai>=0.1.0->rag_evaluation==0.2.1) (1.0.5)\n",
      "Requirement already satisfied: h11<0.15,>=0.13 in c:\\python312\\lib\\site-packages (from httpcore==1.*->httpx<1.0.0,>=0.28.1->google-genai>=0.1.0->rag_evaluation==0.2.1) (0.14.0)\n",
      "Requirement already satisfied: annotated-types>=0.6.0 in c:\\python312\\lib\\site-packages (from pydantic<3.0.0,>=2.0.0->google-genai>=0.1.0->rag_evaluation==0.2.1) (0.7.0)\n",
      "Requirement already satisfied: pydantic-core==2.23.4 in c:\\python312\\lib\\site-packages (from pydantic<3.0.0,>=2.0.0->google-genai>=0.1.0->rag_evaluation==0.2.1) (2.23.4)\n",
      "Requirement already satisfied: six>=1.5 in c:\\python312\\lib\\site-packages (from python-dateutil>=2.8.2->pandas>=1.0->rag_evaluation==0.2.1) (1.16.0)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in c:\\users\\hp\\appdata\\roaming\\python\\python312\\site-packages (from requests<3.0.0,>=2.28.1->google-genai>=0.1.0->rag_evaluation==0.2.1) (3.3.2)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in c:\\python312\\lib\\site-packages (from requests<3.0.0,>=2.28.1->google-genai>=0.1.0->rag_evaluation==0.2.1) (2.2.1)\n",
      "Requirement already satisfied: colorama in c:\\python312\\lib\\site-packages (from tqdm->openai>=0.27->rag_evaluation==0.2.1) (0.4.6)\n",
      "Requirement already satisfied: aiohappyeyeballs>=2.3.0 in c:\\python312\\lib\\site-packages (from aiohttp->openai>=0.27->rag_evaluation==0.2.1) (2.4.3)\n",
      "Requirement already satisfied: aiosignal>=1.1.2 in c:\\python312\\lib\\site-packages (from aiohttp->openai>=0.27->rag_evaluation==0.2.1) (1.3.1)\n",
      "Requirement already satisfied: attrs>=17.3.0 in c:\\users\\hp\\appdata\\roaming\\python\\python312\\site-packages (from aiohttp->openai>=0.27->rag_evaluation==0.2.1) (23.2.0)\n",
      "Requirement already satisfied: frozenlist>=1.1.1 in c:\\python312\\lib\\site-packages (from aiohttp->openai>=0.27->rag_evaluation==0.2.1) (1.4.1)\n",
      "Requirement already satisfied: multidict<7.0,>=4.5 in c:\\python312\\lib\\site-packages (from aiohttp->openai>=0.27->rag_evaluation==0.2.1) (6.1.0)\n",
      "Requirement already satisfied: yarl<2.0,>=1.12.0 in c:\\python312\\lib\\site-packages (from aiohttp->openai>=0.27->rag_evaluation==0.2.1) (1.13.1)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in c:\\users\\hp\\appdata\\roaming\\python\\python312\\site-packages (from jinja2->torch>=2.0.0->rag_evaluation==0.2.1) (2.1.5)\n",
      "Requirement already satisfied: mpmath>=0.19 in c:\\python312\\lib\\site-packages (from sympy->torch>=2.0.0->rag_evaluation==0.2.1) (1.3.0)\n",
      "Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in c:\\python312\\lib\\site-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0,>=2.14.1->google-genai>=0.1.0->rag_evaluation==0.2.1) (0.6.1)\n",
      "Using cached rag_evaluation-0.2.1-py3-none-any.whl (9.7 kB)\n",
      "Using cached accelerate-1.8.1-py3-none-any.whl (365 kB)\n",
      "Using cached google_genai-1.25.0-py3-none-any.whl (226 kB)\n",
      "Using cached anyio-4.9.0-py3-none-any.whl (100 kB)\n",
      "Using cached google_auth-2.40.3-py2.py3-none-any.whl (216 kB)\n",
      "Using cached httpx-0.28.1-py3-none-any.whl (73 kB)\n",
      "Using cached cachetools-5.5.2-py3-none-any.whl (10 kB)\n",
      "Using cached pyasn1_modules-0.4.2-py3-none-any.whl (181 kB)\n",
      "Using cached rsa-4.9.1-py3-none-any.whl (34 kB)\n",
      "Installing collected packages: rsa, pyasn1-modules, cachetools, anyio, httpx, google-auth, google-genai, accelerate, rag_evaluation\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  WARNING: Failed to write executable - trying to use .deleteme logic\n",
      "ERROR: Could not install packages due to an OSError: [WinError 2] The system cannot find the file specified: 'C:\\\\Python312\\\\Scripts\\\\pyrsa-decrypt.exe' -> 'C:\\\\Python312\\\\Scripts\\\\pyrsa-decrypt.exe.deleteme'\n",
      "\n",
      "WARNING: There was an error checking the latest version of pip.\n"
     ]
    }
   ],
   "source": [
    "!pip install rag_evaluation==0.2.1"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting google-genai\n",
      "  Obtaining dependency information for google-genai from https://files.pythonhosted.org/packages/f6/ec/149f3d49b56cf848142071772aabb1c290b535bd9b5327a5dfccf1d00332/google_genai-1.25.0-py3-none-any.whl.metadata\n",
      "  Using cached google_genai-1.25.0-py3-none-any.whl.metadata (41 kB)\n",
      "Requirement already satisfied: anyio<5.0.0,>=4.8.0 in c:\\python312\\lib\\site-packages (from google-genai) (4.9.0)\n",
      "Collecting google-auth<3.0.0,>=2.14.1 (from google-genai)\n",
      "  Obtaining dependency information for google-auth<3.0.0,>=2.14.1 from https://files.pythonhosted.org/packages/17/63/b19553b658a1692443c62bd07e5868adaa0ad746a0751ba62c59568cd45b/google_auth-2.40.3-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_auth-2.40.3-py2.py3-none-any.whl.metadata (6.2 kB)\n",
      "Collecting httpx<1.0.0,>=0.28.1 (from google-genai)\n",
      "  Obtaining dependency information for httpx<1.0.0,>=0.28.1 from https://files.pythonhosted.org/packages/2a/39/e50c7c3a983047577ee07d2a9e53faf5a69493943ec3f6a384bdc792deb2/httpx-0.28.1-py3-none-any.whl.metadata\n",
      "  Using cached httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)\n",
      "Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in c:\\python312\\lib\\site-packages (from google-genai) (2.9.2)\n",
      "Requirement already satisfied: requests<3.0.0,>=2.28.1 in c:\\users\\hp\\appdata\\roaming\\python\\python312\\site-packages (from google-genai) (2.32.2)\n",
      "Requirement already satisfied: tenacity<9.0.0,>=8.2.3 in c:\\python312\\lib\\site-packages (from google-genai) (8.5.0)\n",
      "Requirement already satisfied: websockets<15.1.0,>=13.0.0 in c:\\python312\\lib\\site-packages (from google-genai) (15.0.1)\n",
      "Requirement already satisfied: typing-extensions<5.0.0,>=4.11.0 in c:\\python312\\lib\\site-packages (from google-genai) (4.12.2)\n",
      "Requirement already satisfied: idna>=2.8 in c:\\users\\hp\\appdata\\roaming\\python\\python312\\site-packages (from anyio<5.0.0,>=4.8.0->google-genai) (3.7)\n",
      "Requirement already satisfied: sniffio>=1.1 in c:\\python312\\lib\\site-packages (from anyio<5.0.0,>=4.8.0->google-genai) (1.3.1)\n",
      "Requirement already satisfied: cachetools<6.0,>=2.0.0 in c:\\python312\\lib\\site-packages (from google-auth<3.0.0,>=2.14.1->google-genai) (5.5.2)\n",
      "Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\\python312\\lib\\site-packages (from google-auth<3.0.0,>=2.14.1->google-genai) (0.4.2)\n",
      "Requirement already satisfied: rsa<5,>=3.1.4 in c:\\python312\\lib\\site-packages (from google-auth<3.0.0,>=2.14.1->google-genai) (4.9.1)\n",
      "Requirement already satisfied: certifi in c:\\users\\hp\\appdata\\roaming\\python\\python312\\site-packages (from httpx<1.0.0,>=0.28.1->google-genai) (2024.2.2)\n",
      "Requirement already satisfied: httpcore==1.* in c:\\python312\\lib\\site-packages (from httpx<1.0.0,>=0.28.1->google-genai) (1.0.5)\n",
      "Requirement already satisfied: h11<0.15,>=0.13 in c:\\python312\\lib\\site-packages (from httpcore==1.*->httpx<1.0.0,>=0.28.1->google-genai) (0.14.0)\n",
      "Requirement already satisfied: annotated-types>=0.6.0 in c:\\python312\\lib\\site-packages (from pydantic<3.0.0,>=2.0.0->google-genai) (0.7.0)\n",
      "Requirement already satisfied: pydantic-core==2.23.4 in c:\\python312\\lib\\site-packages (from pydantic<3.0.0,>=2.0.0->google-genai) (2.23.4)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in c:\\users\\hp\\appdata\\roaming\\python\\python312\\site-packages (from requests<3.0.0,>=2.28.1->google-genai) (3.3.2)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in c:\\python312\\lib\\site-packages (from requests<3.0.0,>=2.28.1->google-genai) (2.2.1)\n",
      "Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in c:\\python312\\lib\\site-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0,>=2.14.1->google-genai) (0.6.1)\n",
      "Using cached google_genai-1.25.0-py3-none-any.whl (226 kB)\n",
      "Using cached google_auth-2.40.3-py2.py3-none-any.whl (216 kB)\n",
      "Using cached httpx-0.28.1-py3-none-any.whl (73 kB)\n",
      "Installing collected packages: httpx, google-auth, google-genai\n",
      "Successfully installed google-auth-2.40.3 google-genai-1.25.0 httpx-0.28.1\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING: Ignoring invalid distribution ~ttpx (C:\\Python312\\Lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution ~ttpx (C:\\Python312\\Lib\\site-packages)\n",
      "  WARNING: The script httpx.exe is installed in 'C:\\Users\\HP\\AppData\\Roaming\\Python\\Python312\\Scripts' which is not on PATH.\n",
      "  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.\n",
      "ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n",
      "ollama 0.4.1 requires httpx<0.28.0,>=0.27.0, but you have httpx 0.28.1 which is incompatible.\n",
      "WARNING: There was an error checking the latest version of pip.\n"
     ]
    }
   ],
   "source": [
    "# pip install --upgrade google-genai\n",
    "\n",
    "import sys\n",
    "!{sys.executable} -m pip install --user --upgrade google-genai\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "_NamespacePath(['C:\\\\Python312\\\\Lib\\\\site-packages\\\\google'])\n"
     ]
    },
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'google.genai'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[10], line 3\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01mgoogle\u001b[39;00m\n\u001b[0;32m      2\u001b[0m \u001b[38;5;28mprint\u001b[39m(google\u001b[38;5;241m.\u001b[39m__path__)             \u001b[38;5;66;03m# should show no __init__.py file\u001b[39;00m\n\u001b[1;32m----> 3\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01mgoogle\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mgenai\u001b[39;00m\n\u001b[0;32m      4\u001b[0m \u001b[38;5;28mprint\u001b[39m(google\u001b[38;5;241m.\u001b[39mgenai\u001b[38;5;241m.\u001b[39m\u001b[38;5;18m__name__\u001b[39m)       \u001b[38;5;66;03m# should print “google.genai”\u001b[39;00m\n",
      "\u001b[1;31mModuleNotFoundError\u001b[0m: No module named 'google.genai'"
     ]
    }
   ],
   "source": [
    "import google\n",
    "print(google.__path__)             # should show no __init__.py file\n",
    "import google.genai\n",
    "print(google.genai.__name__)       # should print “google.genai”\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "C:\\Python312\\python.exe\n",
      "['C:\\\\Python312\\\\python312.zip', 'C:\\\\Python312\\\\DLLs', 'C:\\\\Python312\\\\Lib', 'C:\\\\Python312', '', 'C:\\\\Users\\\\HP\\\\AppData\\\\Roaming\\\\Python\\\\Python312\\\\site-packages', 'C:\\\\Python312\\\\Lib\\\\site-packages', 'C:\\\\Python312\\\\Lib\\\\site-packages\\\\win32', 'C:\\\\Python312\\\\Lib\\\\site-packages\\\\win32\\\\lib', 'C:\\\\Python312\\\\Lib\\\\site-packages\\\\Pythonwin']\n"
     ]
    }
   ],
   "source": [
    "import sys\n",
    "print(sys.executable)\n",
    "print(sys.path)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "ename": "ImportError",
     "evalue": "cannot import name 'genai' from 'google' (unknown location)",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mImportError\u001b[0m                               Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[9], line 2\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[38;5;66;03m# import evaluate_response\u001b[39;00m\n\u001b[1;32m----> 2\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mrag_evaluation\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mevaluator\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m evaluate_response\n",
      "File \u001b[1;32m~\\Desktop\\rag_eval_package\\rag_evaluation\\rag_evaluation\\__init__.py:9\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[38;5;124;03m\"\"\"\u001b[39;00m\n\u001b[0;32m      2\u001b[0m \u001b[38;5;124;03mRAG Evaluation package\u001b[39;00m\n\u001b[0;32m      3\u001b[0m \n\u001b[0;32m      4\u001b[0m \u001b[38;5;124;03mProvides tools for evaluating Retrieval-Augmented Generation (RAG) projects\u001b[39;00m\n\u001b[0;32m      5\u001b[0m \u001b[38;5;124;03mby scoring generated responses across various metrics.\u001b[39;00m\n\u001b[0;32m      6\u001b[0m \u001b[38;5;124;03m\"\"\"\u001b[39;00m\n\u001b[0;32m      8\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mconfig\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m get_api_key\n\u001b[1;32m----> 9\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mevaluator\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m (evaluate_all, evaluate_response,\n\u001b[0;32m     10\u001b[0m                             evaluate_openai, evaluate_gemini,)\n\u001b[0;32m     11\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mmetrics\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m (\n\u001b[0;32m     12\u001b[0m     EVALUATION_PROMPT_TEMPLATE,\n\u001b[0;32m     13\u001b[0m     QUERY_RELEVANCE_CRITERIA, QUERY_RELEVANCE_STEPS,\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m     17\u001b[0m     FLUENCY_SCORE_CRITERIA, FLUENCY_SCORE_STEPS,\n\u001b[0;32m     18\u001b[0m )\n\u001b[0;32m     19\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mutils\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m normalize_score, calculate_weighted_accuracy, generate_report\n",
      "File \u001b[1;32m~\\Desktop\\rag_eval_package\\rag_evaluation\\rag_evaluation\\evaluator.py:5\u001b[0m\n\u001b[0;32m      3\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01mopenai\u001b[39;00m\n\u001b[0;32m      4\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01mtorch\u001b[39;00m\n\u001b[1;32m----> 5\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mgoogle\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m genai\n\u001b[0;32m      6\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mgoogle\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mgenai\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m types\n\u001b[0;32m      7\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mtransformers\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m AutoTokenizer, AutoModelForCausalLM\n",
      "\u001b[1;31mImportError\u001b[0m: cannot import name 'genai' from 'google' (unknown location)"
     ]
    }
   ],
   "source": [
    "# import evaluate_response\n",
    "from rag_evaluation.evaluator import evaluate_response"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "!pip install -e path/to/your/rag_evaluation\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "id": "LVrMcMSsDqDF"
   },
   "source": [
    "# Examples with different OpenAI models"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/",
     "height": 237
    },
    "id": "d6BwYoZU3NAb",
    "outputId": "6dd59ab5-2ebb-4f52-899d-72855989ca86"
   },
   "outputs": [],
   "source": [
    "# use rag-evaluation\n",
    "\n",
    "# Input strings\n",
    "query = question\n",
    "response = llm_response\n",
    "document = wikipedia_text\n",
    "\n",
    "# Get evaluation results\n",
    "evaluate_response(\n",
    "        query,\n",
    "        response,\n",
    "        document,\n",
    "        model_type=\"openai\",\n",
    "        model_name='gpt-4o',\n",
    "        )\n",
    "\n",
    "# Note that no model was explicitly provided as an argument here, because the default model is `gpt-4o-mini`\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/",
     "height": 237
    },
    "id": "Ee2o4bTU4Aj3",
    "outputId": "19e12d56-581c-4c55-c05b-0628a4d04ca5"
   },
   "outputs": [],
   "source": [
    "# use rag-evaluation\n",
    "\n",
    "# Input strings\n",
    "query = question\n",
    "response = llm_response\n",
    "document = wikipedia_text\n",
    "\n",
    "# Get evaluation results\n",
    "evaluate_response(\n",
    "        query,\n",
    "        response,\n",
    "        document,\n",
    "        model_type=\"openai\",\n",
    "        model_name='gpt-4o',\n",
    "    )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/",
     "height": 237
    },
    "id": "Lq9Gjwht4jvj",
    "outputId": "486002a4-d20e-40b3-c0a4-ee8af0996561"
   },
   "outputs": [],
   "source": [
    "# use rag-evaluation\n",
    "\n",
    "# Input strings\n",
    "query = question\n",
    "response = llm_response\n",
    "document = wikipedia_text\n",
    "\n",
    "# Get evaluation results\n",
    "evaluate_response(\n",
    "        query,\n",
    "        response,\n",
    "        document,\n",
    "        model_type=\"openai\",\n",
    "        model_name='gpt-4o',\n",
    "    )"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "id": "liUUvjAp-IAj"
   },
   "source": [
    "# Example with Difference Question and answer"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "id": "uCVcnIFN6Rb3"
   },
   "outputs": [],
   "source": [
    "question2 = \"What do large language models inherit from the data they are trained on?\"\n",
    "\n",
    "human_response = \"\"\"\n",
    "Some inheritance in large language models related to the data they are trained on include inheriting inaccuracies and biases present in the training data.\n",
    "\"\"\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/",
     "height": 237
    },
    "id": "qpiNeq266-1X",
    "outputId": "f10b008d-b315-408f-c433-318ad644572b"
   },
   "outputs": [],
   "source": [
    "# use rag_evaluation\n",
    "\n",
    "# Input strings\n",
    "query = question2\n",
    "response = human_response\n",
    "document = wikipedia_text\n",
    "\n",
    "# Get evaluation results\n",
    "evaluate_response(\n",
    "        query,\n",
    "        response,\n",
    "        document,\n",
    "        model_type=\"openai\",\n",
    "        model_name='gpt-4.1'\n",
    "    )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "id": "Xk54BHTfAspB"
   },
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "id": "pgBtHoutAuDb"
   },
   "source": [
    "## Example with Query-Response Mismatch\n",
    "\n",
    "\n",
    "The question that matches the response is Question 1, as seen in the initial sample. However, we now replace Question 1 with  Question 2 to see how the metric evaluates it.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/",
     "height": 237
    },
    "id": "XocqRhE3_3hB",
    "outputId": "4b75f81d-9e4d-4a9a-e27d-5ffdb8df56d6"
   },
   "outputs": [],
   "source": [
    "# Input strings\n",
    "query = question2\n",
    "response = llm_response\n",
    "document = wikipedia_text\n",
    "\n",
    "# Get evaluation results\n",
    "evaluate_response(\n",
    "        query,\n",
    "        response,\n",
    "        document,\n",
    "        model_type=\"openai\",\n",
    "        model_name='gpt-4o'\n",
    "    )"
   ]
  }
 ],
 "metadata": {
  "colab": {
   "provenance": []
  },
  "kernelspec": {
   "display_name": "venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
